### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [oxidusnake/mod_0_skills#1]
@oxidusnake there are some issues in your assessment that show gaps in your understanding of the mod 0 material. I'd like to give you another shot at this:
* [x] Create a class 3 file and a class 3 example object file, and for this 3rd class:
  * [x] Make sure that all of your data is syntactically correct
  * [x] Make sure that your methods either modify an attribute or use an attribute to perform a calculation

I'd recommend you watch the session 4 recording again as a refresher before attempting this 3rd class

**Comment by MarchCorbin** [comment]
Hi David, I have updated the files as per requested. Please let me know if this is more along the lines you are looking for. Also, sorry for not getting this back by Sunday evening I was working on my capstone on Saturday and didn't check my slack channel until Monday morning. I know the staff is on break now (or at least i'm assuming) but hopefully these changes will meet your expectations. Again, I apologize for the delay and will check my slack channel daily moving forward.

**Comment by damwhit** [comment]
@oxidusnake , this is closer, but there are some more updates I'd like for you to make. Make sure you're paying attention to detail on these changes.
* As it currently stands, in your `class_3_example_object.txt` file, your `cost` and `refills` attributes are the only ones with correct syntax for their data. 
* [x] Please fix your data in all of the other attributes and methods. ie. if it's a string, there should be quotes, if its an array, there should be brackets and the contained data in the array should also be correct etc.
* Your middle two methods make sense to me, however the 1st and 4th methods do not. I would not expect the totalCapacity of a cup to change, however, the currentCapacity would.
* [x] How would you change the `fillCup` method to make more sense. Hint: it's in one of the lesson plans. Please change your file to reflect that.
* [x] If anything, I'd expect `addIce` to add to the `currentCapacity` attribute. What other attribute would be effected? Please update your file to reflect those changes.

**Comment by damwhit** [comment]
Hi Corbin, these changes are good enough to make you `technical ready`. However, I do want to point out that your useIngredients method doesn't make sense as it currently stands. How might you change it so that we have a return value? Also, your full attribute has underlying data. What does that tell you about it?

**Comment by damwhit** [comment]
I would recommend going over session 4 again to answer the above questions. And possibly watch the recording as well. Happy to answer any questions that come up!
